'use client';

import Link from 'next/link';
import { useState, useEffect } from 'react';

export default function ExportPage() {
  const [selectedFormat, setSelectedFormat] = useState('mp4');
  const [selectedResolution, setSelectedResolution] = useState('1080p');
  const [includeAudio, setIncludeAudio] = useState(true);
  const [includeSubtitles, setIncludeSubtitles] = useState(true);
  const [exportProgress, setExportProgress] = useState(82);

  useEffect(() => {
    const interval = setInterval(() => {
      setExportProgress(prev => {
        if (prev >= 100) {
          alert('Export complete!');
          return 100;
        }
        return prev + 1;
      });
    }, 300);
    return () => clearInterval(interval);
  }, []);
  return (
    <main className="pt-6 pb-12 max-w-[1440px] mx-auto px-6 grid grid-cols-1 lg:grid-cols-12 gap-8">
      {/* Main Content Area: Video Preview */}
      <section className="lg:col-span-8 space-y-6">
        <div className="relative group aspect-video rounded-xl overflow-hidden bg-black shadow-2xl border border-outline-variant/10">
          <img alt="Film Preview" className="w-full h-full object-cover opacity-90" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDF8O7XdqoJWVQHA40LlHpiN1NkZ32lGz9e-fF2kTgci7UJ1lRzFXmVFISo9hURf5slBCHC2d5bG9zVu1s5lOLVvVhn5TP1Gzf2znHuyPIwVAoVrWOgZsWQYLjPacG3IZnSxjQnNd2CndLjnY3RJyvJa-9Nu9NQKvFJoCZm3tdHu7NVx6-1lN8Qj_T0tL9_Lsiu1_Lj4s9DV7_XqIRPOzYR_za4LMNw_cqIDxAvc131VAkQ3S1vSjlk8dQDcYe47emBnvGY5npAQ18" />
          {/* Video Overlay Controls */}
          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent flex flex-col justify-end p-6 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="flex items-center gap-4 w-full">
              <button className="text-white hover:text-primary transition-colors">
                <span className="material-symbols-outlined text-4xl" style={{fontVariationSettings: "'FILL' 1"}}>play_arrow</span>
              </button>
              <div className="flex-grow h-1.5 bg-white/20 rounded-full relative overflow-hidden">
                <div className="absolute inset-y-0 left-0 bg-primary w-2/3"></div>
              </div>
              <span className="text-xs font-mono text-white">02:45 / 04:12</span>
              <button className="text-white hover:text-primary transition-colors">
                <span className="material-symbols-outlined">fullscreen</span>
              </button>
            </div>
          </div>
        </div>

        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-3xl font-headline font-extrabold tracking-tight text-white">THE SILENT NEBULA</h1>
            <p className="text-on-surface-variant mt-1">Generated by Director AI Engine v4.2 • Cinematic Sci-Fi</p>
          </div>
          <div className="flex gap-2">
            <span className="px-3 py-1 rounded-full bg-primary-container/20 text-primary text-xs font-bold flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
              READY TO EXPORT
            </span>
          </div>
        </div>

        {/* Export Configuration Bento Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-6 rounded-xl bg-surface-container-low border border-outline-variant/10 space-y-4">
            <h3 className="text-sm font-headline font-bold uppercase tracking-widest text-on-surface-variant">Output Settings</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <label className="text-sm font-medium">Format</label>
                <select
                  value={selectedFormat}
                  onChange={(e) => setSelectedFormat(e.target.value)}
                  className="bg-surface-container-highest border-none rounded-lg text-sm px-4 py-2 focus:ring-1 focus:ring-primary/50 text-white"
                >
                  <option value="mp4">MP4 (H.264)</option>
                  <option value="mov">MOV (ProRes)</option>
                  <option value="webm">WebM</option>
                </select>
              </div>
              <div className="flex items-center justify-between">
                <label className="text-sm font-medium">Resolution</label>
                <div className="flex p-1 bg-surface-container-highest rounded-lg">
                  <button
                    onClick={() => setSelectedResolution('1080p')}
                    className={`px-4 py-1 text-xs font-bold rounded-md transition ${
                      selectedResolution === '1080p'
                        ? 'bg-primary text-on-primary'
                        : 'bg-surface-container text-on-surface-variant hover:text-on-surface'
                    }`}
                  >
                    1080p
                  </button>
                  <button
                    onClick={() => setSelectedResolution('4k')}
                    className={`px-4 py-1 text-xs font-bold rounded-md transition ${
                      selectedResolution === '4k'
                        ? 'bg-primary text-on-primary'
                        : 'bg-surface-container text-on-surface-variant hover:text-on-surface'
                    }`}
                  >
                    4K
                  </button>
                </div>
              </div>
            </div>
          </div>

          <div className="p-6 rounded-xl bg-surface-container-low border border-outline-variant/10 space-y-4">
            <h3 className="text-sm font-headline font-bold uppercase tracking-widest text-on-surface-variant">Audio & Text</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-tertiary">subtitles</span>
                  <span className="text-sm font-medium">Burn-in Subtitles</span>
                </div>
                <input
                  checked={includeSubtitles}
                  onChange={(e) => setIncludeSubtitles(e.target.checked)}
                  className="w-10 h-5 bg-surface-container-highest rounded-full border-none text-primary focus:ring-0 cursor-pointer"
                  type="checkbox"
                />
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-tertiary">graphic_eq</span>
                  <span className="text-sm font-medium">Dolby Atmos Render</span>
                </div>
                <input
                  checked={includeAudio}
                  onChange={(e) => setIncludeAudio(e.target.checked)}
                  className="w-10 h-5 bg-surface-container-highest rounded-full border-none text-primary focus:ring-0 cursor-pointer"
                  type="checkbox"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Sidebar: Export & Upsell */}
      <aside className="lg:col-span-4 space-y-6">
        {/* Pro Upsell Card */}
        <div className="p-6 rounded-xl bg-gradient-to-br from-tertiary-container/10 to-surface-container border border-tertiary/20 relative overflow-hidden group">
          <div className="absolute -right-4 -top-4 w-24 h-24 bg-tertiary/10 rounded-full blur-3xl group-hover:bg-tertiary/20 transition-all"></div>
          <div className="flex items-start gap-4 relative z-10">
            <div className="bg-tertiary-container p-2 rounded-lg">
              <span className="material-symbols-outlined text-on-tertiary-container" style={{fontVariationSettings: "'FILL' 1"}}>workspace_premium</span>
            </div>
            <div>
              <h4 className="font-headline font-bold text-white">Go Pro for Clean Film</h4>
              <p className="text-sm text-on-surface-variant mt-1">Remove the Director AI watermark and unlock 8K exporting.</p>
              <button className="mt-4 text-xs font-bold text-tertiary hover:underline uppercase tracking-widest flex items-center gap-1">
                Upgrade Now
                <span className="material-symbols-outlined text-sm">arrow_forward</span>
              </button>
            </div>
          </div>
        </div>

        {/* Export Final Action */}
        <div className="p-6 rounded-xl bg-surface-container-high border border-outline-variant/10 space-y-6">
          <div className="space-y-2">
            <div className="flex justify-between text-xs font-bold text-on-surface-variant uppercase tracking-widest">
              <span>Exporting Sequence</span>
              <span>82%</span>
            </div>
            <div className="h-2 bg-surface-container-highest rounded-full overflow-hidden">
              <div className="h-full bg-gradient-to-r from-primary to-primary-container w-[82%] shadow-[0_0_12px_rgba(255,144,100,0.5)]"></div>
            </div>
          </div>
          <button onClick={() => alert(`Exporting as ${selectedFormat.toUpperCase()} at ${selectedResolution}...`)} className="w-full bg-gradient-to-br from-primary to-primary-container py-4 rounded-xl text-on-primary font-headline font-black text-lg shadow-lg hover:shadow-primary/20 active:scale-95 transition-all flex items-center justify-center gap-3">
            <span className="material-symbols-outlined">download</span>
            EXPORT FILM
          </button>
          <div className="pt-4 border-t border-outline-variant/15">
            <h5 className="text-xs font-bold text-on-surface-variant uppercase tracking-tighter mb-4 text-center">Share Directly</h5>
            <div className="grid grid-cols-3 gap-3">
              <button onClick={() => navigator.clipboard.writeText('https://director.film/share/the-silent-nebula-xyz123').then(() => alert('Share link copied!'))} className="flex flex-col items-center gap-2 p-3 rounded-lg bg-surface-container-highest hover:bg-surface-bright transition-colors">
                <span className="material-symbols-outlined text-on-surface-variant">link</span>
                <span className="text-[10px] uppercase font-bold text-on-surface-variant">Copy Link</span>
              </button>
              <button onClick={() => window.open('https://wa.me/?text=Check%20out%20my%20film%20THE%20SILENT%20NEBULA%20https%3A%2F%2Fdirector.film%2Fshare%2Fthe-silent-nebula-xyz123')} className="flex flex-col items-center gap-2 p-3 rounded-lg bg-surface-container-highest hover:bg-surface-bright transition-colors">
                <span className="material-symbols-outlined text-on-surface-variant">chat</span>
                <span className="text-[10px] uppercase font-bold text-on-surface-variant">WhatsApp</span>
              </button>
              <button onClick={() => window.open('https://instagram.com')} className="flex flex-col items-center gap-2 p-3 rounded-lg bg-surface-container-highest hover:bg-surface-bright transition-colors">
                <span className="material-symbols-outlined text-on-surface-variant">camera</span>
                <span className="text-[10px] uppercase font-bold text-on-surface-variant">Instagram</span>
              </button>
            </div>
          </div>
        </div>

        {/* Credits Card */}
        <div className="p-6 rounded-xl bg-surface-container-low border border-outline-variant/10">
          <h4 className="text-xs font-bold text-on-surface-variant uppercase tracking-widest mb-4">Metadata</h4>
          <div className="space-y-3">
            <div className="flex justify-between text-sm">
              <span className="text-on-surface-variant">File Size</span>
              <span className="text-white font-mono">1.24 GB</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-on-surface-variant">Duration</span>
              <span className="text-white font-mono">00:04:12</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-on-surface-variant">FPS</span>
              <span className="text-white font-mono">23.976</span>
            </div>
          </div>
        </div>
      </aside>

      {/* Footer Navigation */}
      <div className="col-span-full border-t border-[#494847]/15 pt-6 flex justify-between items-center gap-4">
        <Link href="/create/generating" className="px-8 py-3 rounded-xl bg-surface-container-highest text-white font-headline font-bold transition-all hover:scale-105 active:scale-95">
          Back
        </Link>
        <Link href="/dashboard" className="px-10 py-3 rounded-xl bg-gradient-to-br from-primary to-primary-container text-on-primary-fixed font-headline font-black transition-all hover:scale-105 active:scale-95">
          BACK TO DASHBOARD
        </Link>
      </div>
    </main>
  );
}
